language: python
python:
  - "3.6"

services:

install:
    - pip install -r requirements.txt
env:
    - YOLO_SECRET_KEY=randomkeyfortestskfjksfehgs
    - YOLO_TEST_DATABASE_URL=postgres://postgres@localhost/yolo_test
before_script:
    - psql -c "CREATE DATABASE yolo_test;" -U postgres
script:
    - pep8 application --ignore=E402
    - nosetests application --with-coverage
before_install:

after_success:

cache: pip
