language: python
python:
  - "3.6"

services:

install:
    - pip install -r requirements.txt
env:
    - YOLO_SECRET_KEY=randomkeyfortestskfjksfehgs
before_script:

script:
    - pep8 application --ignore=E402
    - nosetests application --with-coverage
before_install:

after_success:

cache: pip
