language: python
python:
  - "3.6"

services:
    - postgresql
install:
    - pip install -r requirements.txt
env:

before_script:
    - psql -c "CREATE DATABASE yolo_test;" -U postgres
    - export YOLO_TEST_DATABASE_URL=postgresql://postgres@localhost/yolo_test
    - export YOLO_SECRET_KEY=randomkeyfortestskfjksfehgs
script:
    - pep8 application --ignore=E402
    - nosetests application --with-coverage
before_install:

after_success:

cache: pip
