"""empty message

Revision ID: 94d8ea5bc55e
Revises: 1346b380b44a
Create Date: 2017-05-11 12:34:45.884832

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '94d8ea5bc55e'
down_revision = '1346b380b44a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucketlists', sa.Column('_date_created', sa.DateTime(), nullable=False))
    op.add_column('bucketlists', sa.Column('_date_modified', sa.DateTime(), nullable=True))
    op.add_column('bucketlists', sa.Column('search_vector', sqlalchemy_utils.types.ts_vector.TSVectorType(), nullable=True))
    op.create_index('ix_bucketlists_search_vector', 'bucketlists', ['search_vector'], unique=False, postgresql_using='gin')
    op.drop_column('bucketlists', 'date_modified')
    op.drop_column('bucketlists', 'date_created')
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_column('users', 'last_login')
    op.add_column('bucketlists', sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('bucketlists', sa.Column('date_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index('ix_bucketlists_search_vector', table_name='bucketlists')
    op.drop_column('bucketlists', 'search_vector')
    op.drop_column('bucketlists', '_date_modified')
    op.drop_column('bucketlists', '_date_created')
    # ### end Alembic commands ###
